apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-citizen
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /innbygger/isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /innbygger/isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  ingresses:
    - https://samtykke.ekstern.dev.nav.no/innbygger
  tokenx:
    enabled: true
  idporten:
    enabled: true
    clientUri: https://www.ekstern.dev.nav.no
    frontchannelLogoutPath: /innbygger/logout
    postLogoutRedirectURIs:
      - https://samtykke.ekstern.dev.nav.no/innbygger/logout/callback
    accessTokenLifetime: 3600
    sessionLifetime: 3600
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
      errorPath: ""
  env:
    - name: VITE_MOCK_DATA
      value: nei
    - name: VITE_API_PATH
      value: /innbygger/api/citizen
    - name: VITE_API_URL
      value: https://samtykke-api.intern.dev.nav.no
    - name: AUDIENCE
      value: dev-gcp:team-researchops:samtykke-api
    - name: URL
      value: https://samtykke.ekstern.dev.nav.no/innbygger
  accessPolicy:
    outbound:
      external:
        - host: tokendings.dev-gcp.nais.io
      rules:
        - application: samtykke-api