apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-citizen
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /innbygger/isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /innbygger/isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - https://samtykke.labs.nais.io/innbygger
  env:
    - name: VITE_MOCK_DATA
      value: ja
    - name: VITE_API_PATH
      value: /innbygger/api/citizen
    - name: VITE_API_URL
      value: https://samtykke-api.labs.nais.io/citizen