apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-employee
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /ansatt/isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /ansatt/isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  ingresses:
    - https://samtykke.ekstern.dev.nav.no/ansatt
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
    sidecar:
      enabled: true
      autoLogin: true
  env:
    - name: VITE_MOCK_DATA
      value: nei
    - name: VITE_API_PATH
      value: /ansatt/api/employee
    - name: VITE_API_URL
      value: https://samtykke-api.intern.dev.nav.no
    - name: AUDIENCE
      value: dev-gcp:team-researchops:samtykke-api
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
      rules:
        - application: samtykke-api
