apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-employee
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /ansatt/isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /ansatt/isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  ingresses:
    - https://samtykke.dev.nav.no/ansatt
  env:
    - name: VITE_MOCK_DATA
      value: nei
    - name: VITE_API_PATH
      value: /ansatt/api/employee
    - name: VITE_API_URL
      value: https://samtykke-api.dev.intern.nav.no