name: Test and deploy citizen

on:
  push:
    branches: [main]
    #paths: [citizen/**]
env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}-citizen:${{ github.sha }}

jobs:
  test-n-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Yarn install
        working-directory: citizen
        run: yarn install
      - name: Yarn build
        working-directory: citizen
        run: yarn build
      # Run tests
      - uses: cypress-io/github-action@v4
        with:
          install: false
          browser: chrome
          start: VITE_MOCK_DATA=ja && VITE_API_PATH=/innbygger/api/citizen && node server.js
          wait-on: 'http://localhost:3000/innbygger/'
          working-directory: ./citizen
          env: HOST=http://localhost:3000/innbygger/
      # Publish build to ghcr
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: citizen
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
      # Deploy to NAIS
      - name: Deploy to labs-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: .nais/citizen/labs.yaml
          VAR: image=${{ env.DOCKER_IMAGE }}