name: Test and deploy citizen

on:
  push:
    branches: [main]
    paths: [citizen/**, .nais/citizen/**, .github/workflows/citizen.yaml]

jobs:
  build:
    name: Build, push and deploy Docker container
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Yarn install
        working-directory: citizen
        run: yarn install
      # Run tests
      - uses: cypress-io/github-action@v4
        env:
          VITE_MOCK_DATA: ja
        with:
          build: yarn build:mock
          install: false
          browser: chrome
          start: node server.js
          wait-on: 'http://localhost:3000/innbygger/'
          working-directory: ./citizen
          env: 
            HOST=http://localhost:3000/innbygger/
      - name: Yarn build
        working-directory: citizen
        run: yarn build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-researchops
          dockerfile: Dockerfile
          docker_context: citizen
          image_suffix: -citizen
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/citizen/dev.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}