name: Test and deploy employee

on:
  push:
    branches: [main]
    #paths: [employee/**]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
