name: Test and deploy employee

on:
  push:
    branches: [main]
    #paths: [employee/**]
env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}-employee:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Yarn install
        working-directory: employee
        run: yarn install
      # Run tests
      - uses: cypress-io/github-action@v4
        with:
          build: yarn build:mock
          install: false
          browser: chrome
          start: node server.js
          wait-on: 'http://localhost:3000/ansatt/'
          working-directory: ./employee
          env: HOST=http://localhost:3000/ansatt/
      - name: Yarn build
        working-directory: employee
        run: yarn build
      # Publish build to ghcr
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: employee
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
  # Deploy to NAIS
  deploy-to-labs:
    name: Deploy to labs-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          DEPLOY_SERVER: deploy.nais.io:443
          CLUSTER: labs-gcp
          RESOURCE: .nais/employee/labs.yaml
          VAR: image=${{ env.DOCKER_IMAGE }}
  deploy-to-dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/employee/dev.yaml
          VAR: image=${{ env.DOCKER_IMAGE }}
