name: Test and deploy employee

on:
  push:
    branches: [main]
    #paths: [employee/**]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Yarn install
        working-directory: employee
        run: yarn install
      - uses: cypress-io/github-action@v4
        with:
          install: false
          browser: chrome
          build: yarn build
          start: node server.js
          wait-on: 'http://localhost:3000/ansatt/'
          working-directory: ./employee
        env:
          CYPRESS_HOST: 'http://localhost:3000/ansatt/'
